{{- if .Values.kubeconfig }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gardener-metrics-exporter-config
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  kubeconfig: {{ .Values.kubeconfig | b64enc }}
{{- end }}