---
apiVersion: v1
kind: Service
metadata:
  name: gardener-metrics-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: gardener
    role: metrics-exporter
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  ports:
  - protocol: TCP
    port: {{ .Values.server.port }}
    targetPort: {{ .Values.server.port }}